#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to retrieve active network interfaces and their IP addresses
ip_addresses=$(ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -vE "^127.0.0.1")

# Display the obtained IPv4 IPs
echo "$ip_addresses"

